### ISSUE TITLE
Dodajcie pierwszy commit.

### ISSUE THREAD

**Issue by slawomirsk** [MarcinekKochaMatme/Cytatowo#1]

**Comment by slawomirsk** [comment]
Jaki tu spokój...

**Comment by MarcinekKochaMatme** [comment]
Zgadzam się całkowicie, tak jak w temacie. Swoją drogą ekipa w żaden sposób nie potrafi współpracować że o dotrzymaniu terminów nie wspomne. Wstyd na całą kolejówe, nawet ci z Koniora więcej by zrobili.
